<?php
include ("MySQL/MysqlConnect.php");

	$query = "SELECT * FROM `specialities` ORDER BY `speciality_name` ";
	$sql = mysql_query($query) or die(mysql_error());
	if (mysql_num_rows($sql)>0)
   	while ($row = mysql_fetch_assoc($sql))
   		{
		if (substr($row['speciality_name'],0,1)=="7" && $row['lic_stc']>0)
   				{   				$query1 = "SELECT * FROM `users` WHERE `user_id` = '".$row["operator_stc"]."' LIMIT 1 ";
				$sql1 = mysql_query($query1) or die(mysql_error());
				$row1 = mysql_fetch_assoc($sql1);
				$spc_list["stc"][]=array
                						(
                						"spec" => $row["speciality_name"],
                						"name" => $row1["user_surname"]." ".substr($row1["user_name"],0,1).". ".substr($row1["user_patronymic"],0,1).".",
										"coast" => $row["price_stc"],
										"license" => $row["lic_stc"],
										"budget" => $row["budg_stc"],
										"short" => $row["short"],
										"quota" => $row["quota_stc"]
										);
   				}

		if (substr($row['speciality_name'],0,1)=="8" && $row['lic_stc']>0)
   				{   				$query1 = "SELECT * FROM `users` WHERE `user_id` = '".$row["operator_stc"]."' LIMIT 1 ";
				$sql1 = mysql_query($query1) or die(mysql_error());
				$row1 = mysql_fetch_assoc($sql1);
   			    $mag_list["stc"][]=array
                						(
                						"spec" => $row["speciality_name"],
                						"name" => $row1["user_surname"]." ".substr($row1["user_name"],0,1).". ".substr($row1["user_patronymic"],0,1).".",
										"coast" => $row["price_stc"],
										"license" => $row["lic_stc"],
										"budget" => $row["budg_stc"],
										"short" => $row["short"],
										"quota" => $row["quota_stc"]
										);
   				}

		if (substr($row['speciality_name'],0,1)=="7" && $row['lic_zao']>0)
   				{
   				$query1 = "SELECT * FROM `users` WHERE `user_id` = '".$row["operator_zao"]."' LIMIT 1";
				$sql1 = mysql_query($query1) or die(mysql_error());
				$row1 = mysql_fetch_assoc($sql1);
                $spc_list["zao"][]=array
                						(
                						"spec" => $row["speciality_name"],
                						"name" => $row1["user_surname"]." ".substr($row1["user_name"],0,1).". ".substr($row1["user_patronymic"],0,1).".",
										"coast" => $row["price_zao"],
										"license" => $row["lic_zao"],
										"budget" => $row["budg_zao"],
										"short" => $row["short"],
										"quota" => $row["quota_zao"]
										);

	   			}
   		if (substr($row['speciality_name'],0,1)=="8" && $row['lic_zao']>0)
   				{
   				$query1 = "SELECT * FROM `users` WHERE `user_id` = '".$row["operator_zao"]."' LIMIT 1";
				$sql1 = mysql_query($query1) or die(mysql_error());
				$row1 = mysql_fetch_assoc($sql1);
                $mag_list["zao"][]=array
                						(
                						"spec" => $row["speciality_name"],
                						"name" => $row1["user_surname"]." ".substr($row1["user_name"],0,1).". ".substr($row1["user_patronymic"],0,1).".",
										"coast" => $row["price_zao"],
										"license" => $row["lic_zao"],
										"budget" => $row["budg_zao"],
										"short" => $row["short"],
										"quota" => $row["quota_zao"]
										);
   				}
   		}
  /*echo "<pre>";
  print_r($spc_list);
  print_r($mag_list);
  echo "</pre>";*/
/*$spc_list = array(
					"stc" => array
					(
						1 => array ("spec" => "7.030203 Видавнича справа та редагування",
								"name" => "Фальківська Л. П.",
								"coast" => "8500",
								"license" => "50",
								"budget" => "10"),
						2 => array ("spec" => "7.080201 Інформатика",
								"name" => "Кулікович Ю. А.",
								"coast" => "8500",
								"license" => "40",
								"budget" => "5"),
						3 => array ("spec" => "7.050201 Менеджмент організацій",
								"name" => "Кириченко В. В.",
								"coast" => "8200",
								"license" => "25",
								"budget" => "10"),
						4 => array ("spec" => "7.020207 Музична педагогіка і виховання",
								"name" => "Павлоцька І. А.",
								"coast" => "7500",
								"license" => "30",
								"budget" => "8"),
						5 => array ("spec" => "7.010103 ПМСО. Біологія",
								"name" => "Михалєвська І. В.",
								"coast" => "7300",
								"license" => "100",
								"budget" => "39"),
						6 => array ("spec" => "7.010103 ПМСО. Історія",
								"name" => "Рудницький С. В.",
								"coast" => "9000",
								"license" => "150",
								"budget" => "35"),
						7 => array ("spec" => "7.010103 ПМСО. Математика",
								"name" => "Кулікович Ю. А.",
								"coast" => "7300",
								"license" => "75",
								"budget" => "49"),
						8 => array ("spec" => "7.010103 ПМСО. Мова та література (англійська)",
								"name" => "Мокіна А. Г.",
								"coast" => "9800",
								"license" => "145",
								"budget" => "50"),
						9 => array ("spec" => "7.010103 ПМСО. Мова та література (німецька)",
								"name" => "Мокіна А. Г.",
								"coast" => "9800",
								"license" => "25",
								"budget" => "17"),
						10 => array ("spec" => "7.010103 ПМСО. Мова та література (російська)",
								"name" => "Фальківська Л. П.",
								"coast" => "8500",
								"license" => "25",
								"budget" => "14"),
						11 => array ("spec" => "7.010103 ПМСО. Українська мова та література",
								"name" => "Фальківська Л. П.",
								"coast" => "8500",
								"license" => "160",
								"budget" => "75"),
						12 => array ("spec" => "7.010103 ПМСО. Фізика",
								"name" => "Кулікович Ю. А.",
								"coast" => "7300",
								"license" => "50",
								"budget" => "33"),
						13 => array ("spec" => "7.010103 ПМСО. Фізична культура",
								"name" => "Твердохліб Ж. О.",
								"coast" => "7900",
								"license" => "100",
								"budget" => "20"),
						14 => array ("spec" => "7.010103 ПМСО. Хімія",
								"name" => "Михалєвська І. В.",
								"coast" => "7300",
								"license" => "70",
								"budget" => "12"),
						15 => array ("spec" => "7.030507 Переклад",
								"name" => "Мокіна А. Г.",
								"coast" => "11000",
								"license" => "50",
								"budget" => "8"),
						16 => array ("spec" => "7.010102 Початкове навчання",
								"name" => "Павленко В. В.",
								"coast" => "7500",
								"license" => "300",
								"budget" => "55"),
						17 => array ("spec" => "7.010107 Практична психологія",
								"name" => "Кириченко В. В.",
								"coast" => "8200",
								"license" => "120",
								"budget" => "15"),
						18 => array ("spec" => "7.040101 Психологія",
								"name" => "Кириченко В. В.",
								"coast" => "8200",
								"license" => "75",
								"budget" => "11"),
						19 => array ("spec" => "7.010105 Соціальна педагогіка",
								"name" => "Кириченко В. В.",
								"coast" => "7400",
								"license" => "125",
								"budget" => "9")
					),
					"zao" => array
					(
                    	1 => array ("spec" => "7.010101 Дошкільне виховання",
								"name" => "Цюряк І. О.",
								"coast" => "4500",
								"short" => "4500",
								"license" => "50",
								"budget" => "3"),
						2 => array ("spec" => "7.080201 Інформатика",
								"name" => "Брусінська Л. В.",
								"coast" => "4250",
								"license" => "25",
								"budget" => "4"),
						3 => array ("spec" => "7.050201 Менеджмент організацій",
								"name" => "Товщик С. А.",
								"coast" => "4100",
								"license" => "25",
								"budget" => "3"),
						4 => array ("spec" => "7.020207 Музична педагогіка і виховання",
								"name" => "Павлоцька І. А.",
								"coast" => "3750",
								"short" => "4500",
								"license" => "30",
								"budget" => "5"),
						5 => array ("spec" => "7.010103 ПМСО. Біологія",
								"name" => "Матвієнко О. В.",
								"coast" => "3650",
								"license" => "100",
								"budget" => "4"),
						6 => array ("spec" => "7.010103 ПМСО. Історія",
								"name" => "Вітюк І. К.",
								"coast" => "4500",
								"license" => "150",
								"budget" => "6"),
						7 => array ("spec" => "7.010103 ПМСО. Математика",
								"name" => "Брусінська Л. В.",
								"coast" => "3650",
								"license" => "75",
								"budget" => "12"),
						8 => array ("spec" => "7.010103 ПМСО. Мова та література (англійська)",
								"name" => "Елерт А.В.",
								"coast" => "4900",
								"license" => "60",
								"budget" => "8"),
						9 => array ("spec" => "7.010103 ПМСО. Мова та література (німецька)",
								"name" => "Елерт А.В.",
								"coast" => "4900",
								"license" => "25",
								"budget" => "4"),
						10 => array ("spec" => "7.010103 ПМСО. Українська мова та література",
								"name" => "Лотоцька С. В.",
								"coast" => "4250",
								"license" => "160",
								"budget" => "13"),
						11 => array ("spec" => "7.010103 ПМСО. Фізична культура",
								"name" => "Твердохліб Ж. О.",
								"coast" => "3950",
								"license" => "50",
								"budget" => "1"),
						12 => array ("spec" => "7.010103 ПМСО. Хімія",
								"name" => "Матвієнко О. В.",
								"coast" => "3650",
								"license" => "50",
								"budget" => "5"),
						13 => array ("spec" => "7.030507 Переклад",
								"name" => "Елерт А.В.",
								"coast" => "5500",
								"license" => "50",
								"budget" => "2"),
						14 => array ("spec" => "7.010102 Початкове навчання",
								"name" => "Павлоцька І. А.",
								"coast" => "3750",
								"short" => "4500",
								"license" => "300",
								"budget" => "55"),
						15 => array ("spec" => "7.010107 Практична психологія",
								"name" => "Товщик С. А.",
								"coast" => "4100",
								"license" => "120",
								"budget" => "3"),
						16 => array ("spec" => "7.040101 Психологія",
								"name" => "Товщик С. А.",
								"coast" => "4100",
								"license" => "75",
								"budget" => "3"),
						17 => array ("spec" => "7.010105 Соціальна педагогіка",
								"name" => "Товщик С. А.",
								"coast" => "3700",
								"short" => "4500",
								"license" => "125",
								"budget" => "5")
					)
				);*/
/*$mag_list = array(
					"stc" => array
					(
     					1 => array ("spec" => "8.080201 Інформатика",
								"name" => "Перникоза В. М.",
								"coast" => "9000",
								"license" => "10",
								"budget" => "2"),
						2 => array ("spec" => "8.010103 ПМСО. Біологія",
								"name" => "Молотовська Л. А.",
								"coast" => "8000",
								"license" => "25",
								"budget" => "1"),
						3 => array ("spec" => "8.010103 ПМСО. Історія",
								"name" => "Зосімович О. Ю.",
								"coast" => "9200",
								"license" => "25",
								"budget" => "6"),
						4 => array ("spec" => "8.010103 ПМСО. Математика",
								"name" => "Перникоза В. М.",
								"coast" => "8000",
								"license" => "20",
								"budget" => "6"),
						5 => array ("spec" => "8.010103 ПМСО. Мова та література (англійська)",
								"name" => "Хорошун О. О.",
								"coast" => "11000",
								"license" => "35",
								"budget" => "9"),
						6 => array ("spec" => "8.010103 ПМСО. Мова та література (німецька)",
								"name" => "Хорошун О. О.",
								"coast" => "11000",
								"license" => "5",
								"budget" => "1"),
						7 => array ("spec" => "8.010103 ПМСО. Мова та література (російська)",
								"name" => "Малиновська Т. В.",
								"coast" => "9000",
								"license" => "5",
								"budget" => "1"),
						8 => array ("spec" => "8.010103 ПМСО. Українська мова та література",
								"name" => "Малиновська Т. В.",
								"coast" => "9000",
								"license" => "40",
								"budget" => "7"),
						9 => array ("spec" => "8.010103 ПМСО. Фізика",
								"name" => "Перникоза В. М.",
								"coast" => "8000",
								"license" => "10",
								"budget" => "3"),
						10 => array ("spec" => "8.010103 ПМСО. Фізична культура",
								"name" => "Усата Т. Я.",
								"coast" => "8200",
								"license" => "10",
								"budget" => "4"),
						11 => array ("spec" => "8.010103 ПМСО. Хімія",
								"name" => "Молотовська Л. А.",
								"coast" => "8000",
								"license" => "10",
								"budget" => "3"),
						12 => array ("spec" => "8.010102 Початкове навчання",
								"name" => "Орел Л. О.",
								"coast" => "8500",
								"license" => "50",
								"budget" => "4"),
						13 => array ("spec" => "8.040101 Психологія",
								"name" => "Пацалюк К. О.",
								"coast" => "9000",
								"license" => "20",
								"budget" => "5"),
						14 => array ("spec" => "8.010105 Соціальна педагогіка",
								"name" => "Пацалюк К. О.",
								"coast" => "8000",
								"license" => "25",
								"budget" => "3"),
						15 => array ("spec" => "8.010201 Фізичне виховання",
								"name" => "Усата Т. Я.",
								"coast" => "8200",
								"license" => "10",
								"budget" => "0")
					),
					"zao" => array
					(
                    	1 => array ("spec" => "8.010103 ПМСО. Біологія",
								"name" => "Молотовська Л. А.",
								"coast" => "4000",
								"license" => "25",
								"budget" => "5"),
						2 => array ("spec" => "8.010103 ПМСО. Історія",
								"name" => "Зосімович О. Ю.",
								"coast" => "4600",
								"license" => "25",
								"budget" => "2"),
						3 => array ("spec" => "8.010103 ПМСО. Математика",
								"name" => "Перникоза В. М.",
								"coast" => "4000",
								"license" => "20",
								"budget" => "2"),
						4 => array ("spec" => "8.010103 ПМСО. Мова та література (англійська)",
								"name" => "Хорошун О. О.",
								"coast" => "5500",
								"license" => "35",
								"budget" => "2"),
						5 => array ("spec" => "8.010103 ПМСО. Мова та література (німецька)",
								"name" => "Хорошун О. О.",
								"coast" => "5500",
								"license" => "5",
								"budget" => "2"),
						6 => array ("spec" => "8.010103 ПМСО. Мова та література (російська)",
								"name" => "Малиновська Т. В.",
								"coast" => "4500",
								"license" => "5",
								"budget" => "0"),
						7 => array ("spec" => "8.010103 ПМСО. Українська мова та література",
								"name" => "Малиновська Т. В.",
								"coast" => "4500",
								"license" => "40",
								"budget" => "2"),
						8 => array ("spec" => "8.010103 ПМСО. Фізика",
								"name" => "Перникоза В. М.",
								"coast" => "4000",
								"license" => "10",
								"budget" => "0"),
						9 => array ("spec" => "8.010103 ПМСО. Фізична культура",
								"name" => "Усата Т. Я.",
								"coast" => "4100",
								"license" => "10",
								"budget" => "1"),
						10 => array ("spec" => "8.010103 ПМСО. Хімія",
								"name" => "Молотовська Л. А.",
								"coast" => "4000",
								"license" => "10",
								"budget" => "1"),
						11 => array ("spec" => "8.010102 Початкове навчання",
								"name" => "Орел Л. О.",
								"coast" => "4250",
								"license" => "50",
								"budget" => "5"),
						12 => array ("spec" => "8.010105 Соціальна педагогіка",
								"name" => "Пацалюк К. О.",
								"coast" => "4000",
								"license" => "25",
								"budget" => "2"),
						13 => array ("spec" => "8.010201 Фізичне виховання",
								"name" => "Усата Т. Я.",
								"coast" => "4100",
								"license" => "10",
								"budget" => "0")
					)
				);
*/
?>